FROM asimlqt/php-apache:8.3

WORKDIR /var/www/html/

RUN apt update \
    && apt install libzip-dev -y \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
COPY composer.json composer.json
COPY composer.lock composer.lock

RUN groupadd -r user && useradd -r -g user user
USER user

COPY ./apache2.conf.dev /etc/apache2/apache2.conf

# COPY ./000-default.conf /etc/apache2/sites-available/

# COPY ./php.ini /usr/local/etc/php/

COPY ./src .

CMD bash -c "composer install && apache2-foreground"