services:
  web:
    container_name: genjiparkour_website-test
    build: .
    networks:
      - contabo_network
      - genji-network
    
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_NAME=${DB_NAME}
      - X_API_ROOT=${X_API_ROOT}
      - X_API_KEY=${X_API_KEY}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}

networks:
  contabo_network:
    external: true
  genji-network:
    external: true
