services:
  genjiparkour_website-test:
    container_name: genjiparkour_website-test
    build: 
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - caddy-network
      - genji-network
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_NAME=${DB_NAME}
      - X_API_ROOT=${X_API_ROOT}
      - X_API_KEY=${X_API_KEY}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - TRANSLATION_API_KEY=${TRANSLATION_API_KEY}
      - TRANSLATION_API_ROOT=${TRANSLATION_API_ROOT}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - TENOR_API_KEY=${TENOR_API_KEY}
      - GLITCHTIP_DSN=${GLITCHTIP_DSN}
    volumes:
      - /home/nebula/bkan0n/repos/genji.pk/dev/genjiparkour_website/src/assets:/var/www/html/assets

networks:
  caddy-network:
    external: true
  genji-network:
    external: true
