services:
  web:
    container_name: genjiparkour_website
    build: .
    networks:
      - contabo_network
    
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

networks:
  contabo_network:
      external: true