name: Deploy Main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: humbertocrispim/ssh-docker-compose-action@v1.0.0
      name: Remote Deployment with Docker-Compose
      with:
        ssh_host: ${{ secrets.GENJI_PK_HOST }}
        ssh_private_key: ${{ secrets.GENJI_PK_SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.GENJI_PK_SSH_USER }}
        docker_compose_prefix: genji_pk
        docker_compose_filename: docker-compose.prod.yaml
