name: New Dev Deployment

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [dev-init]
  
jobs:
  deploy:
    uses: bkan0n/bkan0n-deploy-workflow/.github/workflows/main.yml@main
    with:
      environment: development
    secrets: inherit