name: New Main Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [ init ]
  
jobs:
  deploy:
    uses: bkan0n/bkan0n-deploy-workflow/.github/workflows/main.yml@main
    with:
      environment: production
      docker_compose_file: docker-compose.prod.yaml
    secrets: inherit

  pull-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Update Assets Volume via Git Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GENJI_PK_HOST }}
          username: ${{ secrets.GENJI_PK_SSH_USER }}
          key: ${{ secrets.GENJI_PK_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/bkan0n/repos/genji.pk/prod/genjiparkour_website
            git pull origin main

  cloudflare-purge:
    runs-on: ubuntu-latest
    steps:
    - name: Purge Cloudflare Cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}